version: "3.8"

services:
  app:
    build:
      context: .
    image: ecommerce_prog
    # command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    command: bash -c "rm -f tmp/pids/server.pid && bin/dev"
    volumes:
      - .:/app
      - projeto_bundle_ingresso:/usr/local/bundle
    ports:
      - 3000:3000
    networks:
      - ingresso_network
    stdin_open: true
    tty: true
    env_file:
      - ${ENV_FILE:-.env}
    depends_on:
      - db

  db:
    image: postgres
    container_name: ingresso_db
    volumes:
      - dataPostgresql:/var/lib/postgresql/data
      # - ./postgresData:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "casa123456Mudar"
    ports:
      - "5435:5432"
    networks:
      - ingresso_network

  # redis:
  #   image: redis:6.0.7
  #   container_name: ecommerce_prog_redis
  #   command: redis-server
  #   # volumes:
  #   #   - redis_data:/data -> isso estava antes troquei
  #   volumes:
  #     - redis_volume_data:/data
  #   ports:
  #     - "6379:6379"
  #   logging:
  #     driver: none
  #   networks:
  #     - ingresso_network

  # sidekiq:
  #   image: ecommerce_prog
  #   container_name: ecommerce_prog_sidekiq
  #   depends_on:
  #     - app
  #     - db
  #     - redis
  #   #mem_limit: 512m
  #   volumes:
  #     - .:/app
  #     - projeto_bundle_ingresso:/usr/local/bundle
  #   command: dotenv -f ".env" bundle exec sidekiq -C config/sidekiq.yml
  #   networks:
  #     - ingresso_network

  mailcatcher:
    image: dockage/mailcatcher:0.9.0
    restart: on-failure
    ports:
    - "1085:1080"
    - "1030:1025"

volumes:
  dataPostgresql:
  # redis_volume_data:
  projeto_bundle_ingresso:

networks:
  ingresso_network:
    name: ingresso_network