require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/additional_food_movies", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # AdditionalFoodMovie. As you add validations to AdditionalFoodMovie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      AdditionalFoodMovie.create! valid_attributes
      get additional_food_movies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      additional_food_movie = AdditionalFoodMovie.create! valid_attributes
      get additional_food_movie_url(additional_food_movie)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_additional_food_movie_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      additional_food_movie = AdditionalFoodMovie.create! valid_attributes
      get edit_additional_food_movie_url(additional_food_movie)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new AdditionalFoodMovie" do
        expect {
          post additional_food_movies_url, params: { additional_food_movie: valid_attributes }
        }.to change(AdditionalFoodMovie, :count).by(1)
      end

      it "redirects to the created additional_food_movie" do
        post additional_food_movies_url, params: { additional_food_movie: valid_attributes }
        expect(response).to redirect_to(additional_food_movie_url(AdditionalFoodMovie.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new AdditionalFoodMovie" do
        expect {
          post additional_food_movies_url, params: { additional_food_movie: invalid_attributes }
        }.to change(AdditionalFoodMovie, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post additional_food_movies_url, params: { additional_food_movie: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested additional_food_movie" do
        additional_food_movie = AdditionalFoodMovie.create! valid_attributes
        patch additional_food_movie_url(additional_food_movie), params: { additional_food_movie: new_attributes }
        additional_food_movie.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the additional_food_movie" do
        additional_food_movie = AdditionalFoodMovie.create! valid_attributes
        patch additional_food_movie_url(additional_food_movie), params: { additional_food_movie: new_attributes }
        additional_food_movie.reload
        expect(response).to redirect_to(additional_food_movie_url(additional_food_movie))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        additional_food_movie = AdditionalFoodMovie.create! valid_attributes
        patch additional_food_movie_url(additional_food_movie), params: { additional_food_movie: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested additional_food_movie" do
      additional_food_movie = AdditionalFoodMovie.create! valid_attributes
      expect {
        delete additional_food_movie_url(additional_food_movie)
      }.to change(AdditionalFoodMovie, :count).by(-1)
    end

    it "redirects to the additional_food_movies list" do
      additional_food_movie = AdditionalFoodMovie.create! valid_attributes
      delete additional_food_movie_url(additional_food_movie)
      expect(response).to redirect_to(additional_food_movies_url)
    end
  end
end
