require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/cinema_movies", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # CinemaMovie. As you add validations to CinemaMovie, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      CinemaMovie.create! valid_attributes
      get cinema_movies_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      cinema_movie = CinemaMovie.create! valid_attributes
      get cinema_movie_url(cinema_movie)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_cinema_movie_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      cinema_movie = CinemaMovie.create! valid_attributes
      get edit_cinema_movie_url(cinema_movie)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new CinemaMovie" do
        expect {
          post cinema_movies_url, params: { cinema_movie: valid_attributes }
        }.to change(CinemaMovie, :count).by(1)
      end

      it "redirects to the created cinema_movie" do
        post cinema_movies_url, params: { cinema_movie: valid_attributes }
        expect(response).to redirect_to(cinema_movie_url(CinemaMovie.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new CinemaMovie" do
        expect {
          post cinema_movies_url, params: { cinema_movie: invalid_attributes }
        }.to change(CinemaMovie, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post cinema_movies_url, params: { cinema_movie: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested cinema_movie" do
        cinema_movie = CinemaMovie.create! valid_attributes
        patch cinema_movie_url(cinema_movie), params: { cinema_movie: new_attributes }
        cinema_movie.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the cinema_movie" do
        cinema_movie = CinemaMovie.create! valid_attributes
        patch cinema_movie_url(cinema_movie), params: { cinema_movie: new_attributes }
        cinema_movie.reload
        expect(response).to redirect_to(cinema_movie_url(cinema_movie))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        cinema_movie = CinemaMovie.create! valid_attributes
        patch cinema_movie_url(cinema_movie), params: { cinema_movie: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested cinema_movie" do
      cinema_movie = CinemaMovie.create! valid_attributes
      expect {
        delete cinema_movie_url(cinema_movie)
      }.to change(CinemaMovie, :count).by(-1)
    end

    it "redirects to the cinema_movies list" do
      cinema_movie = CinemaMovie.create! valid_attributes
      delete cinema_movie_url(cinema_movie)
      expect(response).to redirect_to(cinema_movies_url)
    end
  end
end
