require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/movie_theaters", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # MovieTheater. As you add validations to MovieTheater, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      MovieTheater.create! valid_attributes
      get movie_theaters_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      movie_theater = MovieTheater.create! valid_attributes
      get movie_theater_url(movie_theater)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_movie_theater_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      movie_theater = MovieTheater.create! valid_attributes
      get edit_movie_theater_url(movie_theater)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new MovieTheater" do
        expect {
          post movie_theaters_url, params: { movie_theater: valid_attributes }
        }.to change(MovieTheater, :count).by(1)
      end

      it "redirects to the created movie_theater" do
        post movie_theaters_url, params: { movie_theater: valid_attributes }
        expect(response).to redirect_to(movie_theater_url(MovieTheater.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new MovieTheater" do
        expect {
          post movie_theaters_url, params: { movie_theater: invalid_attributes }
        }.to change(MovieTheater, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post movie_theaters_url, params: { movie_theater: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested movie_theater" do
        movie_theater = MovieTheater.create! valid_attributes
        patch movie_theater_url(movie_theater), params: { movie_theater: new_attributes }
        movie_theater.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the movie_theater" do
        movie_theater = MovieTheater.create! valid_attributes
        patch movie_theater_url(movie_theater), params: { movie_theater: new_attributes }
        movie_theater.reload
        expect(response).to redirect_to(movie_theater_url(movie_theater))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        movie_theater = MovieTheater.create! valid_attributes
        patch movie_theater_url(movie_theater), params: { movie_theater: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested movie_theater" do
      movie_theater = MovieTheater.create! valid_attributes
      expect {
        delete movie_theater_url(movie_theater)
      }.to change(MovieTheater, :count).by(-1)
    end

    it "redirects to the movie_theaters list" do
      movie_theater = MovieTheater.create! valid_attributes
      delete movie_theater_url(movie_theater)
      expect(response).to redirect_to(movie_theaters_url)
    end
  end
end
