# default: &default
#   adapter: postgresql
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   enconding: unicode
#   host: localhost
#   post: 5435
#   username: postgres
#   password: casa123456Mudar

# development:
#   <<: *default
#   database: ingresso_development

# test:
#   <<: *default
#   database: ingresso_test

# production:
#   <<: *default
#   database: ingresso_production

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV["DATABASE_URL"] %>

development:
  <<: *default

test:
  <<: *default

homolog:
  <<: *default

production:
  <<: *default